services:
  eventstore:
    image: eventstore/eventstore:24.10
    environment:
      - EVENTSTORE_INSECURE=True
      - EVENTSTORE_RUN_PROJECTIONS=${EVENTSTORE_RUN_PROJECTIONS:-None}
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=${EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP:-True}
    ports:
      - 1113:1113
      - 2113:2113
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.39.1
    command:
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention=30d
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
      - --web.enable-admin-api
    volumes:
      - ../common/prometheus-config:/etc/prometheus/
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:9.1.7
    depends_on:
      - prometheus
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana-volume:/var/lib/grafana
      - ../common/grafana/provisioning/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ../common/grafana/provisioning/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ../common/grafana/dashboards:/var/lib/grafana-dashboards
    ports:
      - 3000:3000

volumes:
  grafana-volume:
