version: '3'

services:
  eventstore1:
    image: eventstore/eventstore:21.10.8-buster-slim
    env_file:
      - common-variables.env
    environment:
      - EVENTSTORE_GOSSIP_SEED=172.16.1.12:2123,172.16.1.13:2133,172.16.1.14:2143
      - EVENTSTORE_INT_IP=172.16.1.11
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_NODE_PRIORITY=100
    ports:
      - 1113:1113
      - 2113:2113
    networks:
      clusternetwork:
        ipv4_address: 172.16.1.11
    volumes:
      - ./certs:/certs
    restart: unless-stopped

  eventstore2:
    image: eventstore/eventstore:21.10.8-buster-slim
    env_file:
      - common-variables.env
    environment:
      - EVENTSTORE_GOSSIP_SEED=172.16.1.11:2113,172.16.1.13:2133,172.16.1.14:2143
      - EVENTSTORE_INT_IP=172.16.1.12
      - EVENTSTORE_HTTP_PORT=2123
      - EVENTSTORE_EXT_TCP_PORT=1123
    ports:
      - 1123:1123
      - 2123:2123
    depends_on:
      - eventstore1
    networks:
      clusternetwork:
        ipv4_address: 172.16.1.12
    volumes:
      - ./certs:/certs
    restart: unless-stopped
    entrypoint: ['bash', '-c', 'sleep 5 && /opt/eventstore/eventstored']

  eventstore3:
    image: eventstore/eventstore:21.10.8-buster-slim
    env_file:
      - common-variables.env
    environment:
      - EVENTSTORE_GOSSIP_SEED=172.16.1.11:2113,172.16.1.12:2123,172.16.1.14:2143
      - EVENTSTORE_INT_IP=172.16.1.13
      - EVENTSTORE_HTTP_PORT=2133
      - EVENTSTORE_EXT_TCP_PORT=1133
    ports:
      - 1133:1133
      - 2133:2133
    depends_on:
      - eventstore1
    networks:
      clusternetwork:
        ipv4_address: 172.16.1.13
    volumes:
      - ./certs:/certs
    restart: unless-stopped
    entrypoint: ['bash', '-c', 'sleep 5 && /opt/eventstore/eventstored']

  eventstore4:
    image: eventstore/eventstore:21.10.8-buster-slim
    env_file:
      - common-variables.env
    environment:
      - EVENTSTORE_GOSSIP_SEED=172.16.1.11:2113,172.16.1.12:2123,172.16.1.13:2133
      - EVENTSTORE_INT_IP=172.16.1.14
      - EVENTSTORE_HTTP_PORT=2143
      - EVENTSTORE_EXT_TCP_PORT=1143
    ports:
      - 1143:1143
      - 2143:2143
    depends_on:
      - eventstore1
    networks:
      clusternetwork:
        ipv4_address: 172.16.1.14
    volumes:
      - ./certs:/certs
    restart: unless-stopped
    entrypoint: ['bash', '-c', 'sleep 5 && /opt/eventstore/eventstored']

  eventstore-ro-replica:
    image: eventstore/eventstore:21.10.8-buster-slim
    env_file:
      - common-variables.env
    environment:
      - EVENTSTORE_GOSSIP_SEED=172.16.1.11:2113,172.16.1.12:2123,172.16.1.13:2133,172.16.1.14:2143
      - EVENTSTORE_INT_IP=172.16.1.15
      - EVENTSTORE_HTTP_PORT=2153
      - EVENTSTORE_EXT_TCP_PORT=1153
      - EVENTSTORE_READ_ONLY_REPLICA=True
    ports:
      - 1153:1153
      - 2153:2153
    depends_on:
      - eventstore1
    networks:
      clusternetwork:
        ipv4_address: 172.16.1.15
    volumes:
      - ./certs:/certs
    entrypoint: ['bash', '-c', 'sleep 5 && /opt/eventstore/eventstored']

  prometheus:
    image: prom/prometheus:v2.39.1
    command:
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention=30d
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
      - --web.enable-admin-api
    volumes:
      - ../common/prometheus-config:/etc/prometheus/
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:9.1.7
    depends_on:
      - prometheus
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana-volume:/var/lib/grafana
      - ../common/grafana/provisioning/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ../common/grafana/provisioning/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ../common/grafana/dashboards:/var/lib/grafana-dashboards
    ports:
      - 3000:3000

networks:
  clusternetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24

volumes:
  grafana-volume:
